Scrum 1491 2
alliance-genome/agr_literature_service pull request #114
Opened 2022-05-02 22:22 UTC by ianlongden

Another go a different way. Not ready for review. Just trying out a few things.

2022-05-03 16:50 UTC, ianlongden commented
authors, cross_references, editors, mesh_details and mod_reference_types all had table names made singular.  Still to do references, resources and users.

2022-05-03 17:37 UTC, azurebrd commented on backend/app/literature/crud/reference_crud.py
There's still a print statement here

2022-05-03 17:38 UTC, azurebrd commented on backend/app/literature/crud/reference_crud.py
> +    print(reference)
There's still a print statement here

2022-05-03 17:39 UTC, azurebrd commented on backend/app/literature/crud/reference_crud.py
> +        logger.debug("Porcessing mod corpus asso")
typos, but doesn't matter

2022-05-03 17:47 UTC, azurebrd commented on src/xml_processing/tests/pmids_by_mods
> -10022914	3	RGD, FB, WB
I think this file shouldn't change.  It gets changed by the functional tests, but the changes shouldn't get committed.  Maybe we should add to the .gitignore ?

2022-05-03 17:48 UTC, azurebrd commented on src/xml_processing/tests/inputs/alliance_pmids
> -10206683
This file also shouldn't change, but this seems like it hasn't really changed, just moved an indentifier further down

2022-05-03 17:50 UTC, azurebrd requested changes
It looks really good, thanks @ianlongden !  There's a couple of files at the end with comments that they shouldn't change.  I'm pretty sure the first one is okay because the data hasn't changed, but the second one probably shouldn't change.  I could be wrong and it might be okay to have it change.  If you've tested that without the change things don't work, then keep the change.  But I think it's a change generated by the functional test that shouldn't get committed.   All the other comments are minor and fine with me.

2022-05-04 22:57 UTC, ianlongden commented on backend/app/literature/crud/reference_crud.py
> +    print(reference)
Done.

2022-05-06 18:03 UTC, azurebrd approved these changes
That's great, thanks @ianlongden

2022-05-06 18:03 UTC, merged